using System.Text;

namespace ZenohDotNet.Generator;

/// <summary>
/// Generates extension methods for Zenoh operations with typed messages.
/// </summary>
internal static class ExtensionMethodGenerator
{
    public static string Generate(ZenohMessageTypeInfo typeInfo)
    {
        var sb = new StringBuilder();
        var typeName = typeInfo.TypeName;
        var fullTypeName = string.IsNullOrEmpty(typeInfo.Namespace) 
            ? typeName 
            : $"{typeInfo.Namespace}.{typeName}";
        var isStruct = typeInfo.TypeKind == Microsoft.CodeAnalysis.TypeKind.Struct;
        var inModifier = isStruct ? "in " : "";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");

        if (!string.IsNullOrEmpty(typeInfo.Namespace))
        {
            sb.AppendLine($"using {typeInfo.Namespace};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace ZenohDotNet.Generated.Extensions;");
        sb.AppendLine();

        // Generate extension class
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Extension methods for {typeName} Zenoh operations.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public static class {typeName}Extensions");
        sb.AppendLine("{");

        // Publisher extensions (wrapped in #if to check for ZenohDotNet.Native/Client references)
        GeneratePublisherExtensions(sb, typeInfo, fullTypeName, inModifier);

        // Subscriber extensions  
        GenerateSubscriberExtensions(sb, typeInfo, fullTypeName);

        // Session convenience methods
        GenerateSessionExtensions(sb, typeInfo, fullTypeName, isStruct);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GeneratePublisherExtensions(StringBuilder sb, ZenohMessageTypeInfo typeInfo, string fullTypeName, string inModifier)
    {
        var typeName = typeInfo.TypeName;
        var isStruct = typeInfo.TypeKind == Microsoft.CodeAnalysis.TypeKind.Struct;
        var inArg = isStruct ? "in " : "";

        // Native layer extension (sync, zero-copy) - conditional compilation
        sb.AppendLine("#if ZENOHDOTNET_NATIVE");
        sb.AppendLine("    #region Publisher Extensions (Native Layer)");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Publishes a {typeName} message (zero-copy, no heap allocation).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static void Put(this ZenohDotNet.Native.Publisher publisher, {inModifier}{fullTypeName} message)");
        sb.AppendLine("    {");
        sb.AppendLine("        Span<byte> buffer = stackalloc byte[4096];");
        sb.AppendLine($"        var written = {fullTypeName}.SerializeTo({inArg}message, buffer);");
        sb.AppendLine("        publisher.Put(buffer.Slice(0, written));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    #endregion");
        sb.AppendLine("#endif");
        sb.AppendLine();

        // Client layer extension (async)
        sb.AppendLine("#if ZENOHDOTNET_CLIENT");
        sb.AppendLine("    #region Publisher Extensions (Client Layer)");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Publishes a {typeName} message asynchronously.");
        sb.AppendLine("    /// </summary>");
        // NOTE: async methods cannot have 'in' parameters, so we use regular parameter
        sb.AppendLine($"    public static ValueTask PutAsync(this ZenohDotNet.Client.Publisher publisher, {fullTypeName} message, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var bytes = {fullTypeName}.Serialize({inArg}message);");
        sb.AppendLine("        return publisher.PutAsync(bytes, cancellationToken);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Sync Put for client layer (can use 'in')
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Publishes a {typeName} message synchronously (low-latency).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static void Put(this ZenohDotNet.Client.Publisher publisher, {inModifier}{fullTypeName} message)");
        sb.AppendLine("    {");
        sb.AppendLine("        Span<byte> buffer = stackalloc byte[4096];");
        sb.AppendLine($"        var written = {fullTypeName}.SerializeTo({inArg}message, buffer);");
        sb.AppendLine("        publisher.Put(buffer.Slice(0, written));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    #endregion");
        sb.AppendLine("#endif");
        sb.AppendLine();
    }

    private static void GenerateSubscriberExtensions(StringBuilder sb, ZenohMessageTypeInfo typeInfo, string fullTypeName)
    {
        var typeName = typeInfo.TypeName;

        sb.AppendLine("#if ZENOHDOTNET_CLIENT");
        sb.AppendLine("    #region Subscriber Extensions");
        sb.AppendLine();

        // Helper method for Sample deserialization
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Attempts to deserialize a Sample payload as {typeName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static bool TryGetPayloadAs(this ZenohDotNet.Client.Sample sample, out {fullTypeName} result)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return {fullTypeName}.TryDeserialize(sample.Payload, out result);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Gets the Sample payload as {typeName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static {fullTypeName} GetPayloadAs{typeName}(this ZenohDotNet.Client.Sample sample)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return {fullTypeName}.Deserialize(sample.Payload);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    #endregion");
        sb.AppendLine("#endif");
        sb.AppendLine();
    }

    private static void GenerateSessionExtensions(StringBuilder sb, ZenohMessageTypeInfo typeInfo, string fullTypeName, bool isStruct)
    {
        var typeName = typeInfo.TypeName;
        var hasDefaultKey = !string.IsNullOrEmpty(typeInfo.DefaultKey);
        var inArg = isStruct ? "in " : "";

        sb.AppendLine("#if ZENOHDOTNET_CLIENT");
        sb.AppendLine("    #region Session Convenience Methods");
        sb.AppendLine();

        // Session.Publish with default key (if available)
        // NOTE: async methods cannot use 'in' parameter
        if (hasDefaultKey)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// Publishes a {typeName} message using its default key expression.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static async ValueTask PublishAsync(this ZenohDotNet.Client.Session session, {fullTypeName} message, CancellationToken cancellationToken = default)");
            sb.AppendLine("    {");
            sb.AppendLine($"        await using var publisher = await session.DeclarePublisherAsync({fullTypeName}.DefaultKeyExpression, cancellationToken).ConfigureAwait(false);");
            sb.AppendLine($"        await publisher.PutAsync({inArg}message, cancellationToken).ConfigureAwait(false);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Session.Publish with explicit key
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Publishes a {typeName} message to the specified key expression.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static async ValueTask PublishAsync(this ZenohDotNet.Client.Session session, string keyExpression, {fullTypeName} message, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        await using var publisher = await session.DeclarePublisherAsync(keyExpression, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine($"        await publisher.PutAsync({inArg}message, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    #endregion");
        sb.AppendLine("#endif");
    }
}
