// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace ZenohDotNet.Native.FFI
{
    internal static unsafe partial class NativeMethods
    {
#if UNITY_IOS || UNITY_WEBGL
        const string __DllName = "__Internal";
#else
        const string __DllName = "zenoh_ffi";
#endif
        



        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void zenoh_declare_queryable_callback_delegate(void* arg1, void* arg2);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void zenoh_declare_subscriber_callback_delegate(SampleData* arg1, void* arg2);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void zenoh_get_callback_delegate(SampleData* arg1, void* arg2);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void zenoh_liveliness_declare_subscriber_callback_delegate(byte* arg1, bool arg2, void* arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void zenoh_querier_get_callback_delegate(SampleData* arg1, void* arg2);



        /// <summary>
        ///  Gets the last error message.
        ///  Returns NULL if no error occurred.
        ///  The returned string is valid until the next FFI call on the same thread.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_last_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* zenoh_last_error();

        /// <summary>
        ///  Opens a Zenoh session with the given configuration (JSON5 string).
        ///  Pass NULL or empty string for default configuration.
        ///  Returns a pointer on success, NULL on failure.
        ///  Call zenoh_last_error() for error details.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_open", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* zenoh_open(byte* config_json);

        /// <summary>
        ///  Closes a Zenoh session and frees all associated resources.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_close", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void zenoh_close(void* session);

        /// <summary>
        ///  Declares a publisher on the given key expression.
        ///  Returns a pointer on success, NULL on failure.
        ///  Call zenoh_last_error() for error details.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_declare_publisher", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* zenoh_declare_publisher(void* session, byte* key_expr);

        /// <summary>
        ///  Publishes data on the given publisher.
        ///  Returns ZenohError code.
        ///  Call zenoh_last_error() for error details.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_publisher_put", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ZenohError zenoh_publisher_put(void* publisher, byte* payload, nuint payload_len);

        /// <summary>
        ///  Undeclares and frees a publisher.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_undeclare_publisher", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void zenoh_undeclare_publisher(void* publisher);

        /// <summary>
        ///  Declares a subscriber on the given key expression with a callback.
        ///  Returns a pointer on success, NULL on failure.
        ///  Call zenoh_last_error() for error details.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_declare_subscriber", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* zenoh_declare_subscriber(void* session, byte* key_expr, zenoh_declare_subscriber_callback_delegate callback, void* context);

        /// <summary>
        ///  Undeclares and frees a subscriber.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_undeclare_subscriber", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void zenoh_undeclare_subscriber(void* subscriber);

        /// <summary>
        ///  Frees a string allocated by the Zenoh FFI.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void zenoh_free_string(byte* s);

        /// <summary>
        ///  Performs a get query (request-response pattern).
        ///  Returns 0 on success, error code on failure.
        ///  Call zenoh_last_error() for error details.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_get", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ZenohError zenoh_get(void* session, byte* selector, zenoh_get_callback_delegate callback, void* context);

        /// <summary>
        ///  Declares a queryable that responds to get queries.
        ///  Returns a pointer on success, NULL on failure.
        ///  Call zenoh_last_error() for error details.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_declare_queryable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* zenoh_declare_queryable(void* session, byte* key_expr, zenoh_declare_queryable_callback_delegate callback, void* context);

        /// <summary>
        ///  Replies to a query with data.
        ///  The query handle is consumed by this operation.
        ///  Call zenoh_last_error() for error details.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_query_reply", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ZenohError zenoh_query_reply(void* query, byte* key_expr, byte* payload, nuint payload_len);

        /// <summary>
        ///  Gets the selector (key expression) of a query.
        ///  Returns a C string that must be freed with zenoh_free_string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_query_selector", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* zenoh_query_selector(void* query);

        /// <summary>
        ///  Undeclares and frees a queryable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_undeclare_queryable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void zenoh_undeclare_queryable(void* queryable);

        /// <summary>
        ///  Creates default publisher options
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_publisher_options_default", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern PublisherOptions zenoh_publisher_options_default();

        /// <summary>
        ///  Declares a publisher with options.
        ///  Returns a pointer on success, NULL on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_declare_publisher_with_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* zenoh_declare_publisher_with_options(void* session, byte* key_expr, PublisherOptions* options);

        /// <summary>
        ///  Deletes data for a key expression.
        ///  Returns ZenohError code.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_delete", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ZenohError zenoh_delete(void* session, byte* key_expr);

        /// <summary>
        ///  Deletes data using a publisher.
        ///  Returns ZenohError code.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_publisher_delete", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ZenohError zenoh_publisher_delete(void* publisher);

        /// <summary>
        ///  Put data directly on a session (without declaring a publisher).
        ///  Returns ZenohError code.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_put", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ZenohError zenoh_put(void* session, byte* key_expr, byte* payload, nuint payload_len);

        /// <summary>
        ///  Declares a liveliness token for the given key expression.
        ///  Returns a pointer on success, NULL on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_liveliness_declare_token", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* zenoh_liveliness_declare_token(void* session, byte* key_expr);

        /// <summary>
        ///  Undeclares and frees a liveliness token.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_liveliness_undeclare_token", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void zenoh_liveliness_undeclare_token(void* token);

        /// <summary>
        ///  Declares a liveliness subscriber.
        ///  The callback receives (key_expr, is_alive, context).
        ///  Returns a pointer on success, NULL on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_liveliness_declare_subscriber", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* zenoh_liveliness_declare_subscriber(void* session, byte* key_expr, zenoh_liveliness_declare_subscriber_callback_delegate callback, void* context);

        /// <summary>
        ///  Gets the Zenoh ID of the session as a hex string.
        ///  Returns a C string that must be freed with zenoh_free_string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_session_zid", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* zenoh_session_zid(void* session);

        /// <summary>
        ///  Publishes data with encoding on the given publisher.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_publisher_put_with_encoding", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ZenohError zenoh_publisher_put_with_encoding(void* publisher, byte* payload, nuint payload_len, ZenohEncodingId encoding_id);

        /// <summary>
        ///  Puts data directly on a key expression with encoding.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_put_with_encoding", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ZenohError zenoh_put_with_encoding(void* session, byte* key_expr, byte* payload, nuint payload_len, ZenohEncodingId encoding_id);

        /// <summary>
        ///  Puts data with attachment on a key expression.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_put_with_attachment", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ZenohError zenoh_put_with_attachment(void* session, byte* key_expr, byte* payload, nuint payload_len, ZenohAttachmentItem* attachment_items, nuint attachment_count);

        /// <summary>
        ///  Declares a querier for repeated queries on the same key expression.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_declare_querier", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* zenoh_declare_querier(void* session, byte* key_expr);

        /// <summary>
        ///  Performs a get query using the querier.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_querier_get", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ZenohError zenoh_querier_get(void* querier, zenoh_querier_get_callback_delegate callback, void* context);

        /// <summary>
        ///  Undeclares and frees a querier.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "zenoh_undeclare_querier", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void zenoh_undeclare_querier(void* querier);


    }

    /// <summary>
    ///  Publisher options
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct PublisherOptions
    {
        public ZenohCongestionControl congestion_control;
        public ZenohPriority priority;
        [MarshalAs(UnmanagedType.U1)] public bool is_express;
    }

    /// <summary>
    ///  Timestamp structure
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ZenohTimestamp
    {
        /// <summary>
        ///  NTP64 timestamp (seconds since epoch in upper 32 bits, fraction in lower 32 bits)
        /// </summary>
        public ulong time_ntp64;
        /// <summary>
        ///  Unique ID of the timestamp source (first 16 bytes of ZenohId)
        /// </summary>
        public fixed byte id[16];
    }

    /// <summary>
    ///  Attachment key-value pair
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ZenohAttachmentItem
    {
        public byte* key;
        public byte* value;
        public nuint value_len;
    }

    /// <summary>
    ///  Sample data structure passed to subscriber callbacks
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SampleData
    {
        public byte* key_expr;
        public byte* payload_data;
        public nuint payload_len;
        public ZenohSampleKind kind;
        public ZenohEncodingId encoding_id;
        [MarshalAs(UnmanagedType.U1)] public bool timestamp_valid;
        public ZenohTimestamp timestamp;
    }


    /// <summary>
    ///  Congestion control strategy
    /// </summary>
    internal enum ZenohCongestionControl : uint
    {
        /// <summary>
        ///  Block if the buffer is full
        /// </summary>
        Block = 0,
        /// <summary>
        ///  Drop the message if the buffer is full
        /// </summary>
        Drop = 1,
    }

    /// <summary>
    ///  Priority of messages
    /// </summary>
    internal enum ZenohPriority : uint
    {
        RealTime = 1,
        InteractiveHigh = 2,
        InteractiveLow = 3,
        DataHigh = 4,
        Data = 5,
        DataLow = 6,
        Background = 7,
    }

    /// <summary>
    ///  Sample kind (Put or Delete)
    /// </summary>
    internal enum ZenohSampleKind : uint
    {
        Put = 0,
        Delete = 1,
    }

    /// <summary>
    ///  Encoding ID for payload
    /// </summary>
    internal enum ZenohEncodingId : uint
    {
        Empty = 0,
        AppOctetStream = 1,
        TextPlain = 2,
        AppJson = 3,
        TextJson = 4,
        AppCbor = 5,
        AppYaml = 6,
        TextYaml = 7,
        TextXml = 8,
        AppXml = 9,
        TextCsv = 10,
        AppProtobuf = 11,
        TextHtml = 12,
    }

    /// <summary>
    ///  Error codes
    /// </summary>
    internal enum ZenohError : uint
    {
        Ok = 0,
        InvalidConfig = 1,
        SessionClosed = 2,
        InvalidKeyExpr = 3,
        PutFailed = 4,
        NullPointer = 5,
        Panic = 254,
        Unknown = 255,
    }


}
